[package]
authors = ["Keringar <git@keringar.xyz>"]
name = "ray-tracer"
version = "0.2.0"

[dependencies]
cgmath = "0.16.1"
image = "0.18.0"
rand = "0.4.2"
rayon = "1.0.1"
clap = "2.31.2"
failure = "0.1.1"
